### ISSUE TITLE
Temporary cooldown feature

### ISSUE THREAD

**Issue by OviRei** [Montori/Bottius#165]
**Is your feature request related to a problem? Please describe.**
Right now when a command like headpat or hug is run and theres a cooldown it sends a message like "Slow down mate, your headpat energy needs to charge up again" but it doesn't say how long you have to wait.

**Describe the feature you'd like in detail**
In the cooldown embed instead of saying "Action failed" in the title of the embed change the commands that have a custom cooldown message to have how long you have to wait in the title. For example:

**Bottius** Today at 23:28
You have to wait 30mins to use this command again
Slow down mate, your headpat energy needs to charge up again

Instead of:
**Bottius** Today at 23:69
Action Failed
Slow down mate, your headpat energy needs to charge up again

Or something like this.

**Additional information/context**
None.

**Comment by Montori** [comment]
Issue closed, duplicate of https://github.com/Montori/Bottius/issues/118
