### ISSUE TITLE
handle commands that take a user as an argument better

### ISSUE THREAD

**Issue by Pagwin2** [Montori/Bottius#24]
commands that take users like !!headpat, quest add and stats should allow for a user id or partial name to be passed instead of only allowing user ping also if an id or user provided isn't valid should provide an error message instead of just calling that command on that user

**Comment by Montori** [comment]
Issue will be treated in this issue [ConvertService #33](https://github.com/Montori/Bottius/issues/33)

**Comment by Pagwin2** [comment]
wait did I put this issue then you made the issue you linked and close this one?(idk how to english that sentence probably because I'm tired right now)

**Comment by Montori** [comment]
Yes you put an issue here for me to see and then I phrase an issue that covers all problems you mentioned and maybe stuff that I also come to think of.
