### ISSUE TITLE
Add Repo ISSUE_TEMPLATES

### ISSUE THREAD

**Issue by StrangeRanger** [Montori/Bottius#62]
# BUG REPORT TEMPLATE (something like this)

---
name: Bug report
about: Create a report to help us improve
title: ''
labels: bug, awaiting review
assignees: ''

---

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 * OS: [e.g. Ubuntu]
 * Node.js Version: [e.g. 6.9.0]
 * MongoDB Version: [e.g. 4.2.0]
 * Release Version: [e.g. 1.2.7]

**Additional context**

# FEATURE REQUEST TEMPLATE (something like this)

---
name: Feature request
about: Suggest an idea for this project
title: ''
labels: enhancement, awaiting review
assignees: ''

---

**Is your feature request related to a problem? Please describe.**
If applicable, provide a clear and concise description of what the problem is.

**Describe the feature you'd like in detail**
A clear and concise description of what you want added. Describe how the feature would work and (if you can) explain possible ways the feature could be implemented. 

**Additional information/context**
Add any other context, information, or screenshots about the feature request here.

**Comment by Montori** [comment]
done by @StrangeRanger
