### ISSUE TITLE
A command to disable or enable a command/action

### ISSUE THREAD

**Issue by StrangeRanger** [Montori/Bottius#63]
Create a command that can be used to enable and disable commands and/or actions (by actions, I mean things such as the uwu reactions/responses). It might even be a good idea to create two commands, one that can disable/enable commands on a global level and one to do it on the server level.

**Comment by OviRei** [comment]
Hi, there is Issue #51  for this, thanks for the submission! heh i feel specl for replying now

**Comment by StrangeRanger** [comment]
Alright
